model="facebook/opt-125m"
#model="mistralai/Mistral-7B-v0.1"
#model="/workspace/Instruction_Tuning_OPT_125M/outputs/trained_model"
workspace_volume="devvol"
max_tokens="100"
temperature="0"
VLLM_CPU_KVCACHE_SPACE="4"
VLLM_CPU_OMP_THREADS_BIND="0-4"